### ISSUE TITLE
serial.h is missing

### ISSUE THREAD

**Issue by klugjohannes** [henyxia/turretController#1]
Hi,

I tried to execute the Makefile, but i get 

```
gcc -c -Wall -std=c99 -g -D_BSD_SOURCE -c main.c -o main.o
main.c:8:20: fatal error: serial.h: No such file or directory
 #include "serial.h"
                    ^
compilation terminated.
make: *** [main.o] Error 1
```

Could it be that you forgot to include `serial.h` in the repository?

**Comment by henyxia** [comment]
It seems like this file was not versionned because of a global .gitignore, sorry about that
